# Generated by Django 4.2.9 on 2024-04-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merge_20210408_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_no',
            field=models.CharField(max_length=255),
        ),
    ]
